// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN8bCwANZ2npmXOzfNWrkWs9j-7-K60Og',
    appId: '1:510847203986:web:9d11dc43cf64b686b3444b',
    messagingSenderId: '510847203986',
    projectId: 'prioritytest-4aba4',
    authDomain: 'prioritytest-4aba4.firebaseapp.com',
    storageBucket: 'prioritytest-4aba4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsKAexmWfexM6cLIxCZ7af2hlnweHXFjU',
    appId: '1:510847203986:android:625b2ac1603e9926b3444b',
    messagingSenderId: '510847203986',
    projectId: 'prioritytest-4aba4',
    storageBucket: 'prioritytest-4aba4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDasUmXU9Ath9BES-M1HDJb_644XMtAmUs',
    appId: '1:510847203986:ios:30bb0d2cb5527161b3444b',
    messagingSenderId: '510847203986',
    projectId: 'prioritytest-4aba4',
    storageBucket: 'prioritytest-4aba4.appspot.com',
    iosBundleId: 'com.example.testProject',
  );
}
